### ISSUE TITLE
maybe too many views?

### ISSUE THREAD

**Issue by Robindiddams** [chrisbendel/dubtrackmobile#32]
so I set up settingsView.js which makes mounts LogoutView.js and LoginView.js, which are very similar components, with very similar dependancies. Perhaps we could make the effort to just both of them into SettingsView.js and reduce some redundancy, and also clean it up.

**Comment by Robindiddams** [comment]
perhaps I'm not giving myself into modularization enough, it just feels like they will only ever be used together and so maybe we should bundle them.

**Comment by chrissbendel** [comment]
if you think they can all fit together in one module that should be fine - Totally your call!
